Add new patient
panas-tech/patient-tracker pull request #31
Opened 2020-12-08 06:05 UTC by cfsnsalazar

This resolves #14 

- feat: Add Modal so it can be used across the app
- feat: Add a Patient form so the new patient can be added to firestore

2020-12-08 06:06 UTC, cfsnsalazar commented
@AndresRodH @bpallares  Decidi poner un PR solo con el submit del form pq queria que vieran el model y el submission antes de hacer el list

2020-12-08 06:12 UTC, bpallares reviewed
De hecho podemos usar https://www.npmjs.com/package/react-popper https://popper.js.org/

2020-12-08 06:12 UTC, bpallares commented on src/components/modal/Modal.tsx
> +// interface ModalCustomProps {
I would suggest using https://reactjs.org/docs/portals.html

2020-12-08 06:13 UTC, bpallares commented on src/components/modal/Modal.tsx
> +// interface ModalCustomProps {
De hecho podemos usar https://www.npmjs.com/package/react-popper https://popper.js.org/

2020-12-08 06:16 UTC, cfsnsalazar commented
@bpallares  Eso es para el modal?. Yo solo lo hice con puro CSS usando Tailwind. No estaria mal usar algo mas simple

2020-12-08 06:17 UTC, AndresRodH requested changes
En verdad cosas como modals son un pelo complicado hacer bien reusables, pero podemos empezar con esto

2020-12-08 06:17 UTC, AndresRodH commented on src/components/modal/Modal.tsx
> +        className="modal-close cursor-pointer z-50"
Donde estan definidos estas clases de modal?

2020-12-08 06:17 UTC, AndresRodH commented on src/components/modal/Modal.tsx
> +}: React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement>) {
Si es solo children usa `{ children: React.ReactNode }`

2020-12-08 06:17 UTC, AndresRodH commented on src/components/modal/Modal.tsx
> +  const state = React.useState(false)
Usualmente es recomendable mandar `open()` y `close()` que el setState

2020-12-08 06:17 UTC, AndresRodH commented on src/components/modal/Modal.tsx
> +          <div>{children}</div>
Este div aqui esta de mas

2020-12-08 06:17 UTC, AndresRodH commented on src/components/modal/Modal.tsx
> +      <h2 className="text-2xl font-bold">Titulo</h2>
Si no hay mas header elements esto deberia ser h1 semanticamente

2020-12-08 06:17 UTC, AndresRodH commented on src/components/modal/Modal.tsx
> +    throw Error('Use Toggle functionality needs to be inside a modal')
En verdad esto es mas alla que el toggle. Mas bien `useModal can only be called from within ModalProvider`

2020-12-08 06:17 UTC, cfsnsalazar commented on src/components/modal/Modal.tsx
> +        className="modal-close cursor-pointer z-50"
En components/modal

2020-12-08 06:21 UTC, bpallares commented on src/components/modal/Modal.tsx
> +    throw Error('Use Toggle functionality needs to be inside a modal')
> @bpallares Eso es para el modal?. Yo solo lo hice con puro CSS usando Tailwind. No estaria mal usar algo mas simple

lo que dice andres, por eso sugeri la libreria. Pero si vamos a empezar a usar algo simple empezemos usando `portals` entonces. https://reactjs.org/docs/portals.html

2020-12-08 06:22 UTC, bpallares commented on src/components/modal/Modal.tsx
> +    throw Error('Use Toggle functionality needs to be inside a modal')
porque mi comentario sale aqui wtf

2020-12-08 06:23 UTC, bpallares commented on src/components/modal/Modal.tsx
> +    throw Error('Use Toggle functionality needs to be inside a modal')
Aqui un ejemplo https://dev.to/alexandprivate/your-next-react-modal-with-your-own-usemodal-hook-context-api-3jg7

2020-12-08 06:28 UTC, AndresRodH commented on src/components/modal/Modal.tsx
> +        className="modal-close cursor-pointer z-50"
Sigo sin ver donde estan esas clases jajaja

2020-12-08 06:29 UTC, AndresRodH requested changes

2020-12-08 06:29 UTC, AndresRodH commented on src/components/modal/Modal.tsx
> +      <div className="modal-container bg-white w-11/12 md:max-w-md mx-auto rounded shadow-lg z-50 overflow-y-auto">
Donde estan definidos

`modal`
`modal-close`
`modal-overlay`
`modal-container`
`modal-content`

2020-12-08 06:32 UTC, bpallares commented on src/features/auth/SignInPage.tsx
> +              Iniciar Sessión
Sesión

2020-12-08 06:32 UTC, bpallares commented on src/features/patients/PatientForm.tsx
> +  async function onSubmit(patient: Patient) {
super hyper nit : useCallback

2020-12-08 06:32 UTC, bpallares commented on src/features/patients/type.ts
> +  VENEZUELAN = 'Venezolano',
pon la arepa bro

2020-12-08 06:40 UTC, cfsnsalazar commented on src/components/modal/Modal.tsx
> +      <div className="modal-container bg-white w-11/12 md:max-w-md mx-auto rounded shadow-lg z-50 overflow-y-auto">
En ningun lado. Me estaba guiando por este style 

https://www.tailwindtoolbox.com/components/modal

y copie esas classes innecesariamente

2020-12-08 06:45 UTC, cfsnsalazar commented on src/features/patients/PatientForm.tsx
> +  async function onSubmit(patient: Patient) {
Explicame why?. Es para optimizacion ?

Att: React Noob 👶

2020-12-08 06:46 UTC, cfsnsalazar commented on src/features/patients/type.ts
> +  VENEZUELAN = 'Venezolano',
Ya es universal bro jaja

2020-12-08 06:47 UTC, cfsnsalazar commented on src/components/modal/Modal.tsx
> +    throw Error('Use Toggle functionality needs to be inside a modal')
Voy a crear un ticket espefico para eso

2020-12-08 06:51 UTC, AndresRodH commented
Hay una linea blanca en el screen 
<img width="125" alt="Screen Shot 2020-12-08 at 12 49 50 AM" src="https://user-images.githubusercontent.com/16929001/101450065-8682f280-38ef-11eb-8feb-5739f9ea6c51.png">

2020-12-08 06:56 UTC, cfsnsalazar commented
@AndresRodH no veo la raya 😞

2020-12-08 07:00 UTC, bpallares commented on src/features/patients/PatientForm.tsx
> +  async function onSubmit(patient: Patient) {
Si, para evitar re-renders inecessarios y que la funcion siga siendo la misma across renders. creo q este onsubmit por ahora no lo necesita

2020-12-08 07:03 UTC, AndresRodH requested changes

2020-12-08 07:03 UTC, AndresRodH commented on src/features/patients/PatientForm.tsx
> +            <option value={gender}>{gender}</option>
Acuerdate de los key props cuando haces maps

2020-12-08 07:03 UTC, AndresRodH commented on src/features/patients/PatientForm.tsx
> +            <option value={nationality}>{nationality}</option>
el key prop aqui tambien

2020-12-08 07:03 UTC, AndresRodH commented on src/components/modal/Modal.tsx
> +      <div className="modal-container bg-white w-11/12 md:max-w-md mx-auto rounded shadow-lg z-50 overflow-y-auto">
De repende `lg:max-w-screen-md es suficiente

2020-12-08 07:07 UTC, cfsnsalazar commented on src/components/modal/Modal.tsx
> +      <div className="modal-overlay absolute w-full h-full bg-gray-900 opacity-50"></div>
Este div es para el dark background

2020-12-08 07:10 UTC, AndresRodH commented on src/components/modal/Modal.tsx
> +      <div className="modal-overlay absolute w-full h-full bg-gray-900 opacity-50"></div>
no me habia fijado bien de eso 😬 nvm. Aunque este div puede ser self closing `<div className="..." />`

2020-12-08 07:14 UTC, cfsnsalazar commented on src/components/modal/Modal.tsx
> +      <div className="modal-container bg-white w-11/12 md:max-w-md mx-auto rounded shadow-lg z-50 overflow-y-auto">
Me gusto `w-11/12 max-w-screen-md`. 
 
Fuera de chinazo ...

Asi crece hasta que llega a cierto tamanho

2020-12-08 07:21 UTC, cfsnsalazar commented on src/features/patients/PatientForm.tsx
> +        <select
Queria hacer un component parte para ponerle style a lost options y vaina

Por ahora voy a hacer algo parecido a lo que hiciste en Input

2020-12-08 07:21 UTC, cfsnsalazar commented on src/features/patients/PatientForm.tsx
> +            <option value={gender}>{gender}</option>
100% Kent  hablo de esto que jode . Good catch !

2020-12-08 07:21 UTC, cfsnsalazar commented on src/features/patients/PatientForm.tsx
> +            <option value={nationality}>{nationality}</option>
listo

2020-12-09 03:33 UTC, bpallares approved these changes

2020-12-09 15:34 UTC, AndresRodH approved these changes

2020-12-09 16:09 UTC, merged