Cfsnsalazar/patient list
panas-tech/patient-tracker pull request #34
Opened 2020-12-15 08:01 UTC by cfsnsalazar

feat: Implement patient list
 
* Resolves #13

2020-12-15 12:57 UTC, AndresRodH requested changes

2020-12-15 12:57 UTC, AndresRodH commented on src/features/patients/PatientList.tsx
>            <div className="flex flex-wrap content-center col-span-1">
Te recomendaria dejar de usar este tipo de grid layouts ala bootstrap y empezar a usar flex. Mira lo que darle un span de una columna le hace al pobre boton :'( 
![Screen Shot 2020-12-15 at 6 47 59 AM](https://user-images.githubusercontent.com/16929001/102217060-ac853580-3ea1-11eb-84c9-3ed10da036e4.png)

2020-12-15 12:57 UTC, AndresRodH commented on src/features/patients/PatientListItem.tsx
> +    <li key={patient.id} data-testid={patient.id}>
El key no se pone aqui sino en el map. Te deje un suggestion ahi de como yo hago estas vainas

2020-12-15 12:57 UTC, AndresRodH commented on src/features/patients/PatientList.tsx
> +              <ul className="grid grid-cols-1 lg:grid-cols-2 ">
falta poner el key en los list items. De hecho como yo hago listas asi prefiero poner el componente dentro de un `<li>...</li>` explicitamente aqui
```suggestion
              <ul className="grid grid-cols-1 lg:grid-cols-2 ">
                {patientList.map((patient) => (
                  <li key={patient.id} data-testid={patient.id}>
                    <PatientListItem patient={patient} />
                  </li>
                 ))}
             </ul>
```

2020-12-17 02:08 UTC, cfsnsalazar commented on src/features/patients/PatientList.tsx
>            <div className="flex flex-wrap content-center col-span-1">
Listo ya lo cambie para usar flex . 

poco a poco creciendo 🌱

2020-12-17 12:41 UTC, AndresRodH approved these changes

2020-12-17 19:01 UTC, merged