Cfsnsalazar/issue22
panas-tech/patient-tracker pull request #38
Opened 2020-12-21 22:01 UTC by cfsnsalazar

* Implement form to add doctor to system
* Implement doctor list
* Add ability to delete doctors 

This solved #21 , #22 , #23

2020-12-21 22:03 UTC, AndresRodH commented on src/features/doctors/DoctorForm.tsx
> +    await db.collection('doctors').add(doctor)
Se supone que estos son usuarios, aqui hay mas que hacer como crear cuentas etc

2020-12-21 22:04 UTC, cfsnsalazar commented on src/features/doctors/DoctorForm.tsx
> +    await db.collection('doctors').add(doctor)
Si si . Pero eso va a ser en un issue aparte no ? . Tipo para setear el password y vaina

2020-12-22 07:05 UTC, cfsnsalazar commented on src/features/doctors/DoctorForm.tsx
> +    await db.collection('doctors').add(doctor)
@AndresRodH  Ya agregue los cloud functions para que los usuarios se agreguen al auth  (Create & Delete)

2020-12-22 10:56 UTC, AndresRodH requested changes

2020-12-22 10:56 UTC, AndresRodH commented on functions/src/index.ts
> +  await admin.auth().createUser({
Asignale el id tambien del snapshot, asi ambos usan el mismo uuid.

Corre prettier tambien bro, el formatting esta medio raro

2020-12-22 10:57 UTC, AndresRodH commented
Brutal mi bro 👍 me gustaron los cloud functions

2020-12-26 23:01 UTC, AndresRodH approved these changes

2020-12-27 04:21 UTC, merged